In [1]:
from dask.distributed import Client

client = Client("tcp://127.0.0.1:41875")
client

<Client: 'tcp://127.0.0.1:41875' processes=8 threads=40, memory=169.33 GB>

In [2]:
import numpy as np
import xarray as xr
import dask.array as dsar

In [18]:
G = xr.DataArray(np.random.rand(5,5,5,3,2), 
                 dims=['sig','YC','XC','row','col'])
F = xr.DataArray(np.random.rand(5,5,5,3,2), 
                 dims=['sig','YC','XC','row','col'])

# def calc_tensor(a,b,chunk=None):
#     pinv = xr.DataArray(dsar.map_blocks(np.linalg.pinv, a.data),
#                         dims=['sig','row','col']).chunk({'sig':1})
#     return dsar.map_blocks(np.dot, pinv.data, b.data, chunks=chunk)
G

<xarray.DataArray (sig: 5, YC: 5, XC: 5, row: 3, col: 2)>
array([[[[[6.06491438e-01, 6.22689421e-01],
          [6.72658273e-01, 7.55625019e-01],
          [7.55086932e-01, 1.83399680e-01]],

         [[6.13520186e-02, 3.79609795e-01],
          [6.27907017e-01, 3.40035796e-01],
          [5.73304067e-02, 2.71438805e-01]],

         [[3.37023335e-01, 7.28711832e-01],
          [6.38683514e-01, 1.96119541e-01],
          [9.91744877e-01, 7.89307433e-01]],

         [[9.38776827e-01, 7.70054477e-01],
          [7.58015466e-01, 7.10821629e-01],
          [9.25569105e-01, 2.17224131e-01]],

         [[3.71431260e-01, 4.59407908e-01],
          [9.65717489e-01, 7.33513039e-01],
          [2.56084451e-01, 8.13710197e-01]]],


        [[[1.23522278e-01, 6.75434268e-01],
          [8.07478626e-02, 1.02262735e-01],
          [4.07279348e-01, 4.01371942e-01]],

         [[1.38110283e-01, 3.33651620e-01],
          [5.82064930e-02, 8.58941290e-01],
          [6.68247127e-01, 5.67346478e-01]],

         [[7.80807971e-01, 9.61552696e-02],
          [7.84815651e-01, 4.21412689e-01],
          [8.73978132e-01, 9.86738783e-01]],

         [[5.28360781e-01, 9.04044935e-02],
          [3.82420173e-01, 6.10280295e-01],
          [2.50495284e-01, 3.32759182e-01]],

         [[1.53750016e-01, 4.17280218e-02],
          [9.99131072e-01, 5.32182065e-01],
          [8.83501151e-01, 8.22558973e-01]]],


        [[[1.89632746e-01, 3.59088612e-02],
          [9.21592560e-01, 6.69847530e-01],
          [9.30741002e-01, 7.97027512e-01]],

         [[9.44968449e-01, 1.86876021e-01],
          [2.25676444e-01, 5.95721374e-01],
          [2.18225594e-01, 4.59291160e-01]],

         [[4.80866147e-01, 8.07434728e-01],
          [7.34630495e-01, 6.38005415e-01],
          [3.45336353e-01, 1.40355955e-01]],

         [[6.11442662e-01, 5.61543953e-01],
          [8.01590935e-01, 1.25950296e-01],
          [4.06944505e-02, 7.76529559e-01]],

         [[1.09763420e-01, 2.21868591e-01],
          [8.70667168e-01, 3.43343698e-01],
          [2.46373802e-01, 4.87263027e-01]]],


        [[[1.54120797e-02, 1.13437877e-01],
          [5.28466082e-01, 4.88861427e-01],
          [7.07495662e-01, 1.07616470e-01]],

         [[7.75411020e-01, 4.74393482e-01],
          [7.93896964e-04, 4.06259910e-02],
          [4.67587954e-01, 3.03144231e-01]],

         [[7.33927458e-01, 3.51399145e-01],
          [7.48747734e-01, 1.42545967e-01],
          [8.46954774e-01, 2.31960990e-01]],

         [[6.01850646e-01, 5.05727750e-01],
          [4.91572708e-01, 8.34045275e-01],
          [7.17483811e-01, 8.86828511e-01]],

         [[2.71762271e-01, 3.07923821e-01],
          [4.12250845e-01, 8.48448508e-02],
          [2.53665903e-01, 6.22018813e-01]]],


        [[[1.55193520e-01, 1.80917330e-01],
          [6.11462498e-01, 6.21593787e-01],
          [5.78579434e-01, 9.56164982e-01]],

         [[8.19621076e-01, 8.59733486e-01],
          [5.81069823e-01, 9.43859471e-01],
          [8.08724263e-01, 4.56360512e-01]],

         [[7.36971518e-01, 9.64351051e-01],
          [3.79662949e-01, 7.11737408e-01],
          [7.33767931e-01, 5.58663622e-01]],

         [[8.10659213e-01, 6.65505212e-01],
          [5.39038757e-01, 4.31106377e-01],
          [9.70819838e-01, 8.94455062e-01]],

         [[3.96615786e-01, 3.75327549e-01],
          [9.04127725e-01, 9.48505109e-01],
          [4.71601598e-01, 1.44964610e-01]]]],



       [[[[6.85176378e-01, 8.70524383e-01],
          [3.50478971e-01, 7.31918633e-01],
          [7.69355847e-01, 6.71478939e-03]],

         [[3.18051905e-01, 8.45814210e-01],
          [6.68595221e-02, 2.61633484e-01],
          [9.46057668e-01, 8.32887017e-02]],

         [[2.14057140e-01, 9.02169053e-02],
          [7.01441363e-01, 9.17368906e-01],
          [4.43143096e-01, 7.57572263e-01]],

         [[5.80211864e-01, 5.82806259e-01],
          [9.70835677e-01, 8.44303951e-01],
          [2.15011484e-02, 4.29636278e-01]],

         [[1.90147673e-01, 7.05432834e-01],


In [30]:
def func(self, other):
#     print(self[0], other[0])
    dot = np.dot(self[0,0,0], other[0,0,0])
    return np.expand_dims(dot, (0,1,2))

# dsar.map_blocks(func, G.chunk({'sig':1}).data, F.chunk({'sig':1}).data, chunks=(1,2,2)).compute()

In [14]:
# MPtest = xr.apply_ufunc(calc_tensor, G.chunk({'sig':-1}), F.chunk({'sig':-1}),  
#                         vectorize=True, output_core_dims=[['j','i']], 
#                         input_core_dims=[['sig'],['sig']],
#                         exclude_dims={'sig','sig'},
#                         dask='parallelized', 
#                         output_dtypes=[float,], output_sizes={'j':2,'i':2})
# MPtest
K = calc_tensor(G.chunk({'sig':1}), F.chunk({'sig':1}), chunk=(1,2,2))
K

dask.array<dot, shape=(5, 2, 2), dtype=float64, chunksize=(1, 2, 2), chunktype=numpy.ndarray>

In [15]:
K.compute().shape

ValueError: could not broadcast input array from shape (2,1,2) into shape (1,2,1)

In [20]:
# pinvG = xr.apply_ufunc(np.linalg.pinv, G.chunk({'sig':1}),  
#                         output_core_dims=[['j','i']], 
# #                         input_core_dims=[['sig'],['sig']],
# #                         exclude_dims={'sig','sig'},
#                         dask='parallelized', 
#                         output_dtypes=[float], output_sizes={'j':2,'i':3}).compute()
pinvG = dsar.map_blocks(np.linalg.pinv, G.chunk({'sig':1,'YC':1,'XC':1}).data)
pinvG

dask.array<pinv, shape=(5, 5, 5, 3, 2), dtype=float64, chunksize=(1, 1, 1, 3, 2), chunktype=numpy.ndarray>

In [35]:
pinvGxr = xr.DataArray(pinvG.compute(), dims=['sig','YC','XC','col','row'])
pinvGxr.shape

(5, 5, 5, 2, 3)

In [9]:
G.isel(sig=0).data.dot(pinvGxr.isel(sig=0).data).dot(G.isel(sig=0).data)

array([[0.22487096, 0.43104267],
       [0.81201176, 0.16357969],
       [0.03939046, 0.29061503]])

In [10]:
G.isel(sig=0)

<xarray.DataArray (row: 3, col: 2)>
array([[0.22487096, 0.43104267],
       [0.81201176, 0.16357969],
       [0.03939046, 0.29061503]])
Dimensions without coordinates: row, col

In [32]:
pinvGxr.isel(sig=1,YC=0,XC=0).data.dot(F.isel(sig=1,YC=0,XC=0).data)

array([[0.13732919, 0.21409292],
       [0.53939132, 0.53507632]])

In [33]:
dot = dsar.map_blocks(func, pinvGxr.chunk({'sig':1,'YC':1,'XC':1}).data, 
                      F.chunk({'sig':1,'YC':1,'XC':1}).data, 
                      chunks=(1,1,1,2,2)).compute()
dot[1,0,0]
# def _inner(x, y):
#     result = np.matmul(x[..., np.newaxis, :], y[..., :, np.newaxis])
#     return result[..., 0, 0]

# def inner_product(a, b, dim):
#     return xr.apply_ufunc(_inner, a, b, input_core_dims=[dim, dim], dask='parallelized',
#                          output_dtypes=[float])

# inner_product(pinvGxr.chunk({'sig':-1}), F.chunk({'sig':-1}), ['sig']).compute()

array([[0.13732919, 0.21409292],
       [0.53939132, 0.53507632]])

In [85]:
G1 = xr.DataArray(np.random.rand(5,2,3), 
                  dims=['sig','row','col'])
F1 = xr.DataArray(np.random.rand(5,3,2), 
                  dims=['sig','row','col'])
dsar.map_blocks(np.dot, G1.chunk({'sig':1}).data, 
                F1.chunk({'sig':1}).data).compute().shape

ValueError: could not broadcast input array from shape (2,1,2) into shape (1,2,1)